#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 ]]; then
  printf 'usage: bootstrap_mcp_host.sh REGION RUNTIME_SECRET_ARN STATIC_IP\n' >&2
  exit 2
fi

region="$1"
runtime_secret_arn="$2"
static_ip="$3"
public_host="${static_ip//./-}.sslip.io"

export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y ca-certificates certbot curl nginx python3-certbot-nginx python3-venv unzip

if ! command -v aws >/dev/null 2>&1; then
  architecture="$(uname -m)"
  case "$architecture" in
    x86_64) aws_arch=x86_64 ;;
    aarch64) aws_arch=aarch64 ;;
    *) printf 'unsupported architecture: %s\n' "$architecture" >&2; exit 2 ;;
  esac
  work_dir="$(mktemp -d)"
  trap 'rm -rf -- "$work_dir"' EXIT
  curl --fail --silent --show-error --location \
    "https://awscli.amazonaws.com/awscli-exe-linux-${aws_arch}.zip" \
    --output "$work_dir/awscliv2.zip"
  unzip -q "$work_dir/awscliv2.zip" -d "$work_dir"
  "$work_dir/aws/install"
fi

if ! id continuum >/dev/null 2>&1; then
  useradd --system --home-dir /opt/continuum --shell /usr/sbin/nologin continuum
fi
chown -R continuum:continuum /opt/continuum
if [[ ! -f /opt/continuum/cockroach-ca.crt ]]; then
  printf 'CockroachDB CA certificate is missing from the private package.\n' >&2
  exit 2
fi
chmod 0644 /opt/continuum/cockroach-ca.crt

if [[ ! -f /swapfile ]]; then
  fallocate -l 1G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  printf '/swapfile none swap sw 0 0\n' >> /etc/fstab
fi

python3 -m venv /opt/continuum/.venv
/opt/continuum/.venv/bin/python -m pip install --disable-pip-version-check --upgrade pip
/opt/continuum/.venv/bin/python -m pip install --disable-pip-version-check '/opt/continuum[dev]'

install -d -o continuum -g continuum -m 0700 /run/continuum-mcp
install -m 0644 /dev/null /etc/systemd/system/continuum-mcp.service
cat > /etc/systemd/system/continuum-mcp.service <<EOF
[Unit]
Description=Authenticated Continuum MCP service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=continuum
Group=continuum
RuntimeDirectory=continuum-mcp
RuntimeDirectoryMode=0700
Environment=CONTINUUM_MCP_HOST=127.0.0.1
Environment=CONTINUUM_MCP_PORT=8000
Environment=PYTHONUNBUFFERED=1
ExecStartPre=/opt/continuum/.venv/bin/python /opt/continuum/scripts/load_mcp_secret.py --secret-arn '$runtime_secret_arn' --region '$region' --output /run/continuum-mcp/runtime.env
# The file is generated by ExecStartPre. The optional prefix lets systemd
# start that pre-command before the first copy exists; it is re-read for
# ExecStart after the pre-command completes.
EnvironmentFile=-/run/continuum-mcp/runtime.env
ExecStart=/opt/continuum/.venv/bin/continuum-mcp
Restart=on-failure
RestartSec=3
TimeoutStartSec=120
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=strict
ReadWritePaths=/run/continuum-mcp
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX

[Install]
WantedBy=multi-user.target
EOF

rm -f /etc/nginx/sites-enabled/default
cat > /etc/nginx/sites-available/continuum-mcp <<EOF
limit_req_zone \$binary_remote_addr zone=continuum_mcp:10m rate=5r/s;

server {
    listen 80;
    listen [::]:80;
    server_name $public_host;
    client_max_body_size 64k;

    location = /healthz {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_read_timeout 10s;
    }

    location /mcp {
        limit_req zone=continuum_mcp burst=10 nodelay;
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Host \$host;
        proxy_set_header Authorization \$http_authorization;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 30s;
        proxy_send_timeout 30s;
    }

    location / {
        return 404;
    }
}
EOF
ln -sfn /etc/nginx/sites-available/continuum-mcp /etc/nginx/sites-enabled/continuum-mcp

systemctl daemon-reload
systemctl enable --now continuum-mcp
nginx -t
systemctl enable --now nginx
systemctl reload nginx

certificate_ready=0
for _attempt in 1 2 3 4 5 6; do
  if certbot --nginx --non-interactive --agree-tos \
      --register-unsafely-without-email --redirect --domain "$public_host"; then
    certificate_ready=1
    break
  fi
  sleep 20
done
if [[ "$certificate_ready" -ne 1 ]]; then
  printf 'TLS certificate issuance failed for %s\n' "$public_host" >&2
  exit 1
fi

systemctl restart continuum-mcp
systemctl reload nginx
health_ready=0
for _attempt in 1 2 3 4 5 6 7 8 9 10 11 12; do
  if curl --fail --silent --show-error \
      "https://${public_host}/healthz" >/dev/null; then
    health_ready=1
    break
  fi
  sleep 5
done
if [[ "$health_ready" -ne 1 ]]; then
  printf 'MCP health check failed for %s\n' "$public_host" >&2
  exit 1
fi
